import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import "./globals.css";
import { NavigationMenuCustom } from "@/components/navbar/navbar-custom";

const sarabun = Sarabun({
    subsets: ["thai", "latin"],
    weight: "400"
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${sarabun.className} antialiased`}
            >
                <NavigationMenuCustom />
                {children}
            </body>
        </html>
    );
}
